name: demo

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11
          enable_kvm: true
      - run: nix-shell --run 'npm ci'
      - run: nix-shell --run 'npm run storybook:build'
      - uses: jamesives/github-pages-deploy-action@v4
        with:
          folder: dist
