name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  install:
    name: Installs and configures nix
    runs-on: ubuntu-latest
    steps:
      - name: Checkouts code
        uses: actions/checkout@v2

      - name: Cache Node modules
        uses: actions/cache@v4
        id: node-modules
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11
          enable_kvm: true

      - name: Installs deps
        run: nix-shell --run 'yarn install --frozen-lockfile --immutable'

      - name: Runs demo in background
        run: nix-shell --run 'yarn start -p 3000 &'

      - name: Runs all tests
        run: nix-shell --run 'yarn test'

      - uses: codecov/codecov-action@v2
