name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-24.11
          enable_kvm: true
      - run: nix-shell --run 'yarn install --frozen-lockfile --immutable'
      - run: nix-shell --run 'yarn start -p 3000 &'
      - run: nix-shell --run 'yarn test'
      - uses: codecov/codecov-action@v5
